rootProject.name = "structureblocklib-root"
include("structureblocklib-bukkit-api")
include("structureblocklib-bukkit-core")
include("structureblocklib-bukkit-plugin")
include("structureblocklib-bukkit-sample")
include("structureblocklib-bukkit-core:structureblocklib-bukkit-nms-19R2")
include("structureblocklib-bukkit-core:structureblocklib-bukkit-nms-110R1")
include("structureblocklib-bukkit-core:structureblocklib-bukkit-nms-111R1")
include("structureblocklib-bukkit-core:structureblocklib-bukkit-nms-112R1")
include("structureblocklib-bukkit-core:structureblocklib-bukkit-nms-113R2")
include("structureblocklib-bukkit-core:structureblocklib-bukkit-nms-114R1")
include("structureblocklib-bukkit-core:structureblocklib-bukkit-nms-115R1")