rootProject.name = "structureblocklib-root"
include("structureblocklib-api")
include("structureblocklib-core")
include("structureblocklib-bukkit-api")
include("structureblocklib-bukkit-core")
include("structureblocklib-bukkit-plugin")
include("structureblocklib-bukkit-sample")
include("structureblocklib-bukkit-core:bukkit-nms-109R2")
include("structureblocklib-bukkit-core:bukkit-nms-110R1")
include("structureblocklib-bukkit-core:bukkit-nms-111R1")
include("structureblocklib-bukkit-core:bukkit-nms-112R1")
include("structureblocklib-bukkit-core:bukkit-nms-113R2")
include("structureblocklib-bukkit-core:bukkit-nms-114R1")
include("structureblocklib-bukkit-core:bukkit-nms-115R1")
include("structureblocklib-bukkit-core:bukkit-nms-116R3")
include("structureblocklib-bukkit-core:bukkit-nms-117R1")
